FROM php:5.6-cli
RUN apt-get update -qq && apt-get install -y -qq git
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer

RUN composer install
COPY . /usr/src/slackwolf
WORKDIR /usr/src/slackwolf
#WORKDIR .
CMD [ "php", "./bot.php" ]


#RUN echo "$PWD"